name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        mongodb-version: ["4.0", "4.2"]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Launch MongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: ${{ matrix.mongodb-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
        env: |
          NODE_ENV : development
          APP_HOST : localhost
          APP_PORT : 3000
          SITE_URL : http://localhost:3000
          mangourl : "mongodb://localhost/TestDevelopersDB?retryWrites : true"
          node_port : 3000
          json_indentation : 4
          email_pass : ""
          secret : "MyApp secret"
          email_host : ""
          email_port : 465
          email_user : ""
          email_pass : ""
          logMaxSize : 5242880
          maxFiles : 5
          TESTDBURL : ""
          FACEBOOK_ID : xxx
          FACEBOOK_SECRET : xxx
          GITHUB_ID : xxx
          GITHUB_SECRET : xxx
          GOOGLE_ID : xxx
          GOOGLE_MAP_API_KEY : xxx
          GOOGLE_SECRET : xxx
          HERE_APP_CODE : xxx
          HERE_APP_ID : xxx
          INSTAGRAM_ID : xxx
          INSTAGRAM_SECRET : xxx
          LINKEDIN_ID : xxx
          LINKEDIN_SECRET : xxx
          PAYPAL_CANCEL_URL : xxx
          PAYPAL_ID : xxx
          PAYPAL_RETURN_URL : xxx
          PAYPAL_SECRET : xxx
          TWITTER_KEY : xxx
          TWITTER_SECRET : xxx
          FILE_SIZE : 10
          NbQuestions  :  3
          MAXDBFETCH  :  1024
          excludetest : 'e2e/*'
